version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep Docker images up to date (if you use Docker)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
